Update GitHub Actions workflow for integration testing

diff --git a/.github/workflows/deploy_and_Integration_test.yml b/.github/workflows/deploy_and_Integration_test.yml
--- a/.github/workflows/deploy_and_Integration_test.yml
+++ b/.github/workflows/deploy_and_Integration_test.yml
@@ -8,57 +8,59 @@ on:
     types: [closed]
     branches:
       - develop
+  push:
+    branches: testprintegTest
   workflow_dispatch:
 
 permissions:
   pull-requests: read
 
 jobs:
-  deploy:
-    if: github.event.pull_request.merged == true
-    runs-on: ubuntu-latest
-    steps:        
-      - name: Use Node.js 20.x
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20.x  
+  # deploy:
+  #   if: github.event.pull_request.merged == true
+  #   runs-on: ubuntu-latest
+  #   steps:        
+  #     - name: Use Node.js 20.x
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20.x  
           
-      - name: Login to Cloud Foundry
-        run: |
-          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key \
-          | sudo tee /etc/apt/trusted.gpg.d/cloudfoundry.asc
-          echo "deb https://packages.cloudfoundry.org/debian stable main" \
-          | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
-          sudo apt update
-          sudo apt install cf-cli
-          cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}
+  #     - name: Login to Cloud Foundry
+  #       run: |
+  #         wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key \
+  #         | sudo tee /etc/apt/trusted.gpg.d/cloudfoundry.asc
+  #         echo "deb https://packages.cloudfoundry.org/debian stable main" \
+  #         | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
+  #         sudo apt update
+  #         sudo apt install cf-cli
+  #         cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}
        
-      - name: Clone and prepare projects & Build and deploy
-        run: |
-          git clone --single-branch --branch develop https://github.com/cap-js/sdm.git
-          git clone --single-branch --branch sdmIncidents https://github.com/cap-js/incidents-app.git
-          cd sdm
-          npm pack
-          echo "Current directory"
-          pwd
-          ls
-          mv *.tgz ../incidents-app
-          cd ../incidents-app
-          npm i *.tgz
+  #     - name: Clone and prepare projects & Build and deploy
+  #       run: |
+  #         git clone --single-branch --branch develop https://github.com/cap-js/sdm.git
+  #         git clone --single-branch --branch sdmIncidents https://github.com/cap-js/incidents-app.git
+  #         cd sdm
+  #         npm pack
+  #         echo "Current directory"
+  #         pwd
+  #         ls
+  #         mv *.tgz ../incidents-app
+  #         cd ../incidents-app
+  #         npm i *.tgz
       
-      - name: Build and deploy
-        run: |
-          cd incidents-app
-          wget -P /tmp https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.2.28/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
-          tar -xvzf /tmp/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
-          sudo mv mbt /usr/local/bin/
-          npm i @sap/cds-dk -g
-          mbt build
-          cf install-plugin multiapps -f
-          cf deploy mta_archives/sdmincidents_1.0.0.mtar -f
+  #     - name: Build and deploy
+  #       run: |
+  #         cd incidents-app
+  #         wget -P /tmp https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.2.28/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
+  #         tar -xvzf /tmp/cloud-mta-build-tool_1.2.28_Linux_amd64.tar.gz
+  #         sudo mv mbt /usr/local/bin/
+  #         npm i @sap/cds-dk -g
+  #         mbt build
+  #         cf install-plugin multiapps -f
+  #         cf deploy mta_archives/sdmincidents_1.0.0.mtar -f
 
   integration-test:
-    needs: deploy
+    # needs: deploy
     runs-on: ubuntu-latest
 
     steps:
@@ -70,9 +72,39 @@ jobs:
         with:
           node-version: '20'
 
+      - name: Fetch and Escape Client Secret
+        id: fetch_secret
+        run: |
+          service_instance_guid=$(cf service sdm-incidents-auth --guid)
+          if [ -z "$service_instance_guid" ]; then
+            echo "Error: Unable to retrieve service instance GUID"; exit 1;
+          fi
+          
+          bindings_response=$(cf curl "/v3/service_credential_bindings?service_instance_guids=${service_instance_guid}")
+          binding_guid=$(echo $bindings_response | jq -r '.resources[0].guid')
+          if [ -z "$binding_guid" ]; then
+            echo "Error: Unable to retrieve binding GUID"; exit 1;
+          fi
+          
+          binding_details=$(cf curl "/v3/service_credential_bindings/${binding_guid}/details")
+          
+          clientSecret=$(echo "$binding_details" | jq -r '.credentials.clientsecret')
+          if [ -z "$clientSecret" ] || [ "$clientSecret" == "null" ]; then
+            echo "Error: clientSecret is not set or is null"; exit 1;
+          fi
+          escapedClientSecret=$(echo "$clientSecret" | sed 's/\$/\\$/g')
+          
+          clientID=$(echo "$binding_details" | jq -r '.credentials.clientid')
+          if [ -z "$clientID" ] || [ "$clientID" == "null" ]; then
+            echo "Error: clientID is not set or is null"; exit 1;
+          fi
+          
+          echo "CLIENT_SECRET=${escapedClientSecret}" >> $GITHUB_ENV || echo "CLIENT_SECRET=REDACTED" >> $GITHUB_ENV
+          echo "CLIENT_ID=${clientID}" >> $GITHUB_ENV || echo "CLIENT_ID=REDACTED" >> $GITHUB_ENV
+
       - name: Run integration tests
         run: |
-          appUrl=${{ secrets.CF_ORG }}-${{ secrets.CF_SPACE }}-incidents-srv.cfapps.eu12.hana.ondemand.com
+          appUrl="${{ secrets.CF_ORG }}-${{ secrets.CF_SPACE }}-incidents-srv.cfapps.eu12.hana.ondemand.com"
           echo "app url: ${appUrl}"
           # JSON file path
           JSON_FILE="test/integration/credentials.json"
@@ -80,6 +112,7 @@ jobs:
           jq --arg appUrl "$appUrl" --arg authUrl "${{ secrets.CAPAUTH_URL }}" --arg clientID "${{ env.CLIENT_ID }}" --arg clientSecret "${{ env.CLIENT_SECRET }}" --arg username "${{ secrets.CF_USER }}" --arg password "${{ secrets.CF_PASSWORD }}" --arg noSDMRoleUsername "${{ secrets.NOSDMROLEUSERNAME }}" --arg noSDMRoleUserPassword "${{ secrets.NOSDMROLEUSERPASSWORD }}" \
           '.appUrl = $appUrl | .authUrl = $authUrl | .clientID = $clientID | .clientSecret = $clientSecret | .username = $username | .password = $password | .noSDMRoleUsername = $noSDMRoleUsername | .noSDMRoleUserPassword = $noSDMRoleUserPassword' $JSON_FILE > "temp.json" \
           && mv "temp.json" $JSON_FILE
-          cat $JSON_FILE
-          npm i
-          npm run integration-test 
+          # Redact sensitive fields before printing
+          jq '{ appUrl, authUrl, username, password }' $JSON_FILE | sed 's/"clientID": "[^"]*"/"clientID": "***"/' | sed 's/"clientSecret": "[^"]*"/"clientSecret": "***"/'
+          npm install
+          npm run integration-test
